name: lighthouse

on:
  pull_request:
    branches:
      - develop
    types: [closed]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Setup dependencies
        run: npm ci
        working-directory: ./lighthouse

      - name: run lighthouse
        run: npm run lighthouse
        working-directory: ./lighthouse
        env:
          SPOTIFY_USER_NAME: ${{ secrets.SPOTIFY_USER_NAME }}
          SPOTIFY_PASSWORD: ${{ secrets.SPOTIFY_PASSWORD }}
          SPOTIFY_EDITOR_URL: https://spotify-playlist-editor.fourside.dev/
